// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaL4bxmscGYx0ySzKJ17lFu5Qj0jNCbYI',
    appId: '1:623438032357:web:0ecf4aa4fa47dba9ca530c',
    messagingSenderId: '623438032357',
    projectId: 'acme-task-app',
    authDomain: 'acme-task-app.firebaseapp.com',
    storageBucket: 'acme-task-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3c_L7AJABDmDnrJuGGRfFCnHBwGriqg',
    appId: '1:623438032357:android:1bed49494f0f8a93ca530c',
    messagingSenderId: '623438032357',
    projectId: 'acme-task-app',
    storageBucket: 'acme-task-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDyfNBpdwyRFXQETv4qAJ1obMfs4tIDiM',
    appId: '1:623438032357:ios:e2550a0ae50c5197ca530c',
    messagingSenderId: '623438032357',
    projectId: 'acme-task-app',
    storageBucket: 'acme-task-app.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
